/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f2f4f6",
        "success-muted": "#10b981",
        "on-secondary-container": "#57657a",
        "on-secondary-fixed-variant": "#3a485b",
        "success-bg": "#f0fdf4",
        "on-tertiary-container": "#de915e",
        "on-surface-variant": "#474651",
        "text-muted": "#64748b",
        "on-secondary-fixed": "#0d1c2e",
        "outline-variant": "#c8c5d3",
        "tertiary-fixed": "#ffdbc7",
        "inverse-surface": "#2d3133",
        "on-primary-fixed-variant": "#3e3c8f",
        "on-surface": "#191c1e",
        "danger-bg": "#fff1f2",
        "inverse-primary": "#c3c0ff",
        "surface-container-highest": "#e0e3e5",
        "secondary-fixed-dim": "#b9c7df",
        "primary-fixed-dim": "#c3c0ff",
        "secondary-container": "#d5e3fc",
        "border-subtle": "#e2e8f0",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eff1f3",
        "surface-container": "#eceef0",
        "on-primary-fixed": "#100563",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#312e81",
        "surface-dim": "#d8dadc",
        "error": "#ba1a1a",
        "secondary": "#515f74",
        "primary": "#1a146b",
        "surface-container-high": "#e6e8ea",
        "tertiary-fixed-dim": "#ffb688",
        "danger-muted": "#f43f5e",
        "surface-white": "#ffffff",
        "surface-bright": "#f7f9fb",
        "primary-fixed": "#e2dfff",
        "on-background": "#191c1e",
        "tertiary": "#3e1a00",
        "on-tertiary-fixed": "#311300",
        "on-primary-container": "#9c9af4",
        "surface-tint": "#5654a8",
        "on-tertiary": "#ffffff",
        "background": "#f7f9fb",
        "text-main": "#1e293b",
        "on-tertiary-fixed-variant": "#70380b",
        "outline": "#777682",
        "tertiary-container": "#5f2b00",
        "on-error-container": "#93000a",
        "surface": "#f7f9fb",
        "on-error": "#ffffff",
        "surface-variant": "#e0e3e5",
        "on-primary": "#ffffff",
        "secondary-fixed": "#d5e3fc"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "max-width": "1280px",
        "page-margin": "2rem",
        "gutter": "1.5rem",
        "component-padding": "1.25rem",
        "section-gap": "3rem"
      }
    },
  },
  plugins: [],
};
